export const CREATE_TRANSACTION = 'ENTITIES/TRANSACTIONS/CREATE_TRANSACTION';
export const DELETE_TRANSACTION = 'ENTITIES/TRANSACTIONS/DELETE_TRANSACTION';
export const UPDATE_TRANSACTION = 'ENTITIES/TRANSACTIONS/UPDATE_TRANSACTION';

export const SET_CHECKED = 'ENTITIES/TRANSACTIONS/SET_CHECKED';

export const TRANSACTIONS_ENTITY_ID = 'transactions';

export const CONFIRM_TRANSACTIONS_REQUEST = 'ENTITIES/TRANSACTIONS/CONFIRM_TRANSACTIONS_REQUEST';
export const CONFIRM_TRANSACTIONS_SUCCESS = 'ENTITIES/TRANSACTIONS/CONFIRM_TRANSACTIONS_SUCCESS';
export const CONFIRM_TRANSACTIONS_FAILURE = 'ENTITIES/TRANSACTIONS/CONFIRM_TRANSACTIONS_FAILURE';

export const GET_PRIVATE_KEY_REQUEST = 'ENTITIES/TRANSACTIONS/GET_PRIVATE_KEY_REQUEST';
export const GET_PRIVATE_KEY_SUCCESS = 'ENTITIES/TRANSACTIONS/GET_PRIVATE_KEY_SUCCESS';
export const GET_PRIVATE_KEY_FAILURE = 'ENTITIES/TRANSACTIONS/GET_PRIVATE_KEY_FAILURE';
