export const CREATE_TRIGGER = 'ENTITIES/TRIGGERS/CREATE_TRIGGER';
export const CREATE_TRIGGER_REQUEST = 'ENTITIES/TRIGGERS/CREATE_TRIGGER_REQUEST';
export const CREATE_TRIGGER_SUCCESS = 'ENTITIES/TRIGGERS/CREATE_TRIGGER_SUCCESS';
export const CREATE_TRIGGER_FAILURE = 'ENTITIES/TRIGGERS/CREATE_TRIGGER_FAILURE';

export const DELETE_TRIGGER = 'ENTITIES/TRIGGERS/DELETE_TRIGGER';
export const DELETE_TRIGGER_REQUEST = 'ENTITIES/TRIGGERS/DELETE_TRIGGER_REQUEST';
export const DELETE_TRIGGER_SUCCESS = 'ENTITIES/TRIGGERS/DELETE_TRIGGER_SUCCESS';
export const DELETE_TRIGGER_FAILURE = 'ENTITIES/TRIGGERS/DELETE_TRIGGER_FAILURE';

export const UPDATE_TRIGGER = 'ENTITIES/TRIGGERS/UPDATE_TRIGGER';
export const UPDATE_TRIGGER_REQUEST = 'ENTITIES/TRIGGERS/UPDATE_TRIGGER_REQUEST';
export const UPDATE_TRIGGER_SUCCESS = 'ENTITIES/TRIGGERS/UPDATE_TRIGGER_SUCCESS';
export const UPDATE_TRIGGER_FAILURE = 'ENTITIES/TRIGGERS/UPDATE_TRIGGER_FAILURE';
