export const CREATE_TABLE = 'ENTITIES/TABLES/CREATE_TABLE';
export const CREATE_TABLE_REQUEST = 'ENTITIES/TABLES/CREATE_TABLE_REQUEST';
export const CREATE_TABLE_SUCCESS = 'ENTITIES/TABLES/CREATE_TABLE_SUCCESS';
export const CREATE_TABLE_FAILURE = 'ENTITIES/TABLES/CREATE_TABLE_FAILURE';

export const DELETE_TABLE = 'ENTITIES/TABLES/DELETE_TABLE';
export const DELETE_TABLE_REQUEST = 'ENTITIES/TABLES/DELETE_TABLE_REQUEST';
export const DELETE_TABLE_SUCCESS = 'ENTITIES/TABLES/DELETE_TABLE_SUCCESS';
export const DELETE_TABLE_FAILURE = 'ENTITIES/TABLES/DELETE_TABLE_FAILURE';

export const UPDATE_TABLE = 'ENTITIES/TABLES/UPDATE_TABLE';
export const UPDATE_TABLE_REQUEST = 'ENTITIES/TABLES/UPDATE_TABLE_REQUEST';
export const UPDATE_TABLE_SUCCESS = 'ENTITIES/TABLES/UPDATE_TABLE_SUCCESS';
export const UPDATE_TABLE_FAILURE = 'ENTITIES/TABLES/UPDATE_TABLE_FAILURE';

export const TABLES_ENTITY_ID = 'tables';
