export const CREATE_FIELD = 'ENTITIES/FIELDS/CREATE_FIELD';
export const CREATE_FIELD_REQUEST = 'ENTITIES/FIELDS/CREATE_FIELD_REQUEST';
export const CREATE_FIELD_SUCCESS = 'ENTITIES/FIELDS/CREATE_FIELD_SUCCESS';
export const CREATE_FIELD_FAILURE = 'ENTITIES/FIELDS/CREATE_FIELD_FAILURE';

export const DELETE_FIELD = 'ENTITIES/FIELDS/DELETE_FIELD';
export const DELETE_FIELD_REQUEST = 'ENTITIES/FIELDS/DELETE_FIELD_REQUEST';
export const DELETE_FIELD_SUCCESS = 'ENTITIES/FIELDS/DELETE_FIELD_SUCCESS';
export const DELETE_FIELD_FAILURE = 'ENTITIES/FIELDS/DELETE_FIELD_FAILURE';

export const UPDATE_FIELD = 'ENTITIES/FIELDS/UPDATE_FIELD';
export const UPDATE_FIELD_REQUEST = 'ENTITIES/FIELDS/UPDATE_FIELD_REQUEST';
export const UPDATE_FIELD_SUCCESS = 'ENTITIES/FIELDS/UPDATE_FIELD_SUCCESS';
export const UPDATE_FIELD_FAILURE = 'ENTITIES/FIELDS/UPDATE_FIELD_FAILURE';
