export const CREATE_ACCOUNT_REQUEST = 'ENTITIES/ACCOUNTS/CREATE_ACCOUNT_REQUEST';
export const CREATE_ACCOUNT_FAILURE = 'ENTITIES/ACCOUNTS/CREATE_ACCOUNT_FAILURE';
export const CREATE_ACCOUNT_SUCCESS = 'ENTITIES/ACCOUNTS/CREATE_ACCOUNT_SUCCESS';

export const DELETE_ACCOUNT = 'ENTITIES/ACCOUNTS/DELETE_ACCOUNT';
export const UPDATE_ACCOUNT = 'ENTITIES/ACCOUNTS/UPDATE_ACCOUNT';
