export const CREATE_ACCOUNT_REQUEST = 'ENTITIES/ACCOUNTS/CREATE_ACCOUNT_REQUEST';
export const CREATE_ACCOUNT_FAILURE = 'ENTITIES/ACCOUNTS/CREATE_ACCOUNT_FAILURE';
export const CREATE_ACCOUNT_SUCCESS = 'ENTITIES/ACCOUNTS/CREATE_ACCOUNT_SUCCESS';

export const DELETE_ACCOUNT_REQUEST = 'ENTITIES/ACCOUNTS/DELETE_ACCOUNT_REQUEST';
export const DELETE_ACCOUNT_FAILURE = 'ENTITIES/ACCOUNTS/DELETE_ACCOUNT_FAILURE';
export const DELETE_ACCOUNT_SUCCESS = 'ENTITIES/ACCOUNTS/DELETE_ACCOUNT_SUCCESS';

export const FETCH_ACCOUNTS_REQUEST = 'ENTITIES/ACCOUNTS/FETCH_ACCOUNTS_REQUEST';
export const FETCH_ACCOUNTS_SUCCESS = 'ENTITIES/ACCOUNTS/FETCH_ACCOUNTS_SUCCESS';
export const FETCH_ACCOUNTS_FAILURE = 'ENTITIES/ACCOUNTS/FETCH_ACCOUNTS_FAILURE';

export const UPDATE_ACCOUNT_REQUEST = 'ENTITIES/ACCOUNTS/UPDATE_ACCOUNT_REQUEST';
export const UPDATE_ACCOUNT_FAILURE = 'ENTITIES/ACCOUNTS/UPDATE_ACCOUNT_FAILURE';
export const UPDATE_ACCOUNT_SUCCESS = 'ENTITIES/ACCOUNTS/UPDATE_ACCOUNT_SUCCESS';
