export const CREATE_INDEX = 'ENTITIES/INDEXS/CREATE_INDEX';
export const CREATE_INDEX_REQUEST = 'ENTITIES/INDEXS/CREATE_INDEX_REQUEST';
export const CREATE_INDEX_SUCCESS = 'ENTITIES/INDEXS/CREATE_INDEX_SUCCESS';
export const CREATE_INDEX_FAILURE = 'ENTITIES/INDEXS/CREATE_INDEX_FAILURE';

export const DELETE_INDEX = 'ENTITIES/INDEXS/DELETE_INDEX';
export const DELETE_INDEX_REQUEST = 'ENTITIES/INDEXS/DELETE_INDEX_REQUEST';
export const DELETE_INDEX_SUCCESS = 'ENTITIES/INDEXS/DELETE_INDEX_SUCCESS';
export const DELETE_INDEX_FAILURE = 'ENTITIES/INDEXS/DELETE_INDEX_FAILURE';

export const UPDATE_INDEX = 'ENTITIES/INDEXS/UPDATE_INDEX';
export const UPDATE_INDEX_REQUEST = 'ENTITIES/INDEXS/UPDATE_INDEX_REQUEST';
export const UPDATE_INDEX_SUCCESS = 'ENTITIES/INDEXS/UPDATE_INDEX_SUCCESS';
export const UPDATE_INDEX_FAILURE = 'ENTITIES/INDEXS/UPDATE_INDEX_FAILURE';
