export const FETCH_ENTITIES_REQUEST = 'ENTITIES/FETCH_ENTITIES_REQUEST';
export const FETCH_ENTITIES_SUCCESS = 'ENTITIES/FETCH_ENTITIES_SUCCESS';
export const FETCH_ENTITIES_FAILURE = 'ENTITIES/FETCH_ENTITIES_FAILURE';

export const UPDATE_ENTITIES = 'ENTITIES/UPDATE_ENTITIES';
