export const CREATE_CONNECTION_REQUEST = 'ENTITIES/CONNECTIONS/CREATE_CONNECTION_REQUEST';
export const CREATE_CONNECTION_SUCCESS = 'ENTITIES/CONNECTIONS/CREATE_CONNECTION_SUCCESS';
export const CREATE_CONNECTION_FAILURE = 'ENTITIES/CONNECTIONS/CREATE_CONNECTION_FAILURE';

export const DELETE_CONNECTION_REQUEST = 'ENTITIES/CONNECTIONS/DELETE_CONNECTION_REQUEST';
export const DELETE_CONNECTION_SUCCESS = 'ENTITIES/CONNECTIONS/DELETE_CONNECTION_SUCCESS';
export const DELETE_CONNECTION_FAILURE = 'ENTITIES/CONNECTIONS/DELETE_CONNECTION_FAILURE';

export const FETCH_CONNECTIONS_REQUEST = 'ENTITIES/CONNECTIONS/FETCH_CONNECTIONS_REQUEST';
export const FETCH_CONNECTIONS_SUCCESS = 'ENTITIES/CONNECTIONS/FETCH_CONNECTIONS_SUCCESS';
export const FETCH_CONNECTIONS_FAILURE = 'ENTITIES/CONNECTIONS/FETCH_CONNECTIONS_FAILURE';

export const SET_CONNECTION_ID = 'ENTITIES/CONNECTIONS/SET_CONNECTION_ID';

export const SET_TABLESPACES_REQUEST = 'ENTITIES/CONNECTIONS/SET_TABLESPACES_REQUEST';
export const SET_TABLESPACES_SUCCESS = 'ENTITIES/CONNECTIONS/SET_TABLESPACES_SUCCESS';
export const SET_TABLESPACES_FAILURE = 'ENTITIES/CONNECTIONS/SET_TABLESPACES_FAILURE';
