export const CREATE_CONNECTIONS_REQUEST = 'ENTITIES/CONNECTIONS/CREATE_CONNECTIONS_REQUEST';
export const CREATE_CONNECTIONS_SUCCESS = 'ENTITIES/CONNECTIONS/CREATE_CONNECTIONS_SUCCESS';
export const CREATE_CONNECTIONS_FAILURE = 'ENTITIES/CONNECTIONS/CREATE_CONNECTIONS_FAILURE';

export const FETCH_CONNECTIONS_REQUEST = 'ENTITIES/CONNECTIONS/FETCH_CONNECTIONS_REQUEST';
export const FETCH_CONNECTIONS_SUCCESS = 'ENTITIES/CONNECTIONS/FETCH_CONNECTIONS_SUCCESS';
export const FETCH_CONNECTIONS_FAILURE = 'ENTITIES/CONNECTIONS/FETCH_CONNECTIONS_FAILURE';
