export const FETCH_TABLESPACES_REQUEST = 'VIEWS/CONNECTIONS/FETCH_TABLESPACES_REQUEST';
export const FETCH_TABLESPACES_SUCCESS = 'VIEWS/CONNECTIONS/FETCH_TABLESPACES_SUCCESS';
export const FETCH_TABLESPACES_FAILURE = 'VIEWS/CONNECTIONS/FETCH_TABLESPACES_FAILURE';
