export const CREATE_TABLESPACE = 'ENTITIES/TABLESPACES/CREATE_TABLESPACE';
export const CREATE_TABLESPACE_REQUEST = 'ENTITIES/TABLESPACES/CREATE_TABLESPACE_REQUEST';
export const CREATE_TABLESPACE_SUCCESS = 'ENTITIES/TABLESPACES/CREATE_TABLESPACE_SUCCESS';
export const CREATE_TABLESPACE_FAILURE = 'ENTITIES/TABLESPACES/CREATE_TABLESPACE_FAILURE';

export const DELETE_TABLESPACE = 'ENTITIES/TABLESPACES/DELETE_TABLESPACE';
export const DELETE_TABLESPACE_REQUEST = 'ENTITIES/TABLESPACES/DELETE_TABLESPACE_REQUEST';
export const DELETE_TABLESPACE_SUCCESS = 'ENTITIES/TABLESPACES/DELETE_TABLESPACE_SUCCESS';
export const DELETE_TABLESPACE_FAILURE = 'ENTITIES/TABLESPACES/DELETE_TABLESPACE_FAILURE';

export const UPDATE_TABLESPACE = 'ENTITIES/TABLESPACES/UPDATE_TABLESPACE';
export const UPDATE_TABLESPACE_REQUEST = 'ENTITIES/TABLESPACES/UPDATE_TABLESPACE_REQUEST';
export const UPDATE_TABLESPACE_SUCCESS = 'ENTITIES/TABLESPACES/UPDATE_TABLESPACE_SUCCESS';
export const UPDATE_TABLESPACE_FAILURE = 'ENTITIES/TABLESPACES/UPDATE_TABLESPACE_FAILURE';

export const TABLESPACES_ENTITY_ID = 'tablespaces';
