export const CREATE_TABLESPACE_REQUEST = 'ENTITIES/TABLESPACES/CREATE_TABLESPACE_REQUEST';
export const CREATE_TABLESPACE_SUCCESS = 'ENTITIES/TABLESPACES/CREATE_TABLESPACE_SUCCESS';
export const CREATE_TABLESPACE_FAILURE = 'ENTITIES/TABLESPACES/CREATE_TABLESPACE_FAILURE';


export const TABLESPACES_ENTITY_ID = 'tablespaces';
