export const CREATE_PROGRESS = 'SERVICES/PROGRESS/CREATE_PROGRESS';
export const DELETE_PROGRESS = 'SERVICES/PROGRESS/DELETE_PROGRESS';
export const UPDATE_PROGRESS = 'SERVICES/PROGRESS/UPDATE_PROGRESS';

